version: '3'
services:
  todolist:
    container_name: todolist
    image: todolist
    # restart: always
    env_file: .env
    command: gunicorn todolist:app -w 2 -b :8000
    ports:
      - "8000:8000"
    depends_on:
      - migration
    volumes:
      - .:/code

  migration:
    container_name: migration
    build: .
    image: todolist
    env_file: .env
    command: flask db upgrade
    depends_on:
      - db
    volumes:
      - .:/code

  db:
    image: postgres:9.6.6
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
